# 基础知识
NumPy的主要对象是同构多维数组。它是一个元素表（通常是数字），所有类型都相同，由非负整数元组索引。在NumPy维度中称为 轴 。

例如，3D空间中的点的坐标[1, 2, 1]具有一个轴。该轴有3个元素，所以我们说它的长度为3.在下图所示的例子中，数组有2个轴。第一轴的长度为2，第二轴的长度为3。

[[ 1., 0., 0.],
 [ 0., 1., 2.]]
NumPy的数组类被调用ndarray。它也被别名所知 array。请注意，numpy.array这与标准Python库类不同array.array，后者只处理一维数组并提供较少的功能。ndarray对象更重要的属性是：

ndarray.ndim - 数组的轴（维度）的个数。在Python世界中，维度的数量被称为rank。

ndarray.shape - 数组的维度。这是一个整数的元组，表示每个维度中数组的大小。对于有 n 行和 m 列的矩阵，shape 将是 (n,m)。因此，shape 元组的长度就是rank或维度的个数 ndim。

ndarray.size - 数组元素的总数。这等于 shape 的元素的乘积。

ndarray.dtype - 一个描述数组中元素类型的对象。可以使用标准的Python类型创建或指定dtype。另外NumPy提供它自己的类型。例如numpy.int32、numpy.int16和numpy.float64。

ndarray.itemsize - 数组中每个元素的字节大小。例如，元素为 float64 类型的数组的 itemsize 为8（=64/8），而 complex32 类型的数组的 itemsize 为4（=32/8）。它等于 ndarray.dtype.itemsize 。

ndarray.data - 该缓冲区包含数组的实际元素。通常，我们不需要使用此属性，因为我们将使用索引访问数组中的元素。

In [2]:
# 一个例子
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [5]:
a.dtype.name

'int32'

In [6]:
a.itemsize

4

In [7]:
a.size

15

In [8]:
type(a)

numpy.ndarray

In [9]:
b = np.array([6,7,8])
b

array([6, 7, 8])

In [10]:
type(b)

numpy.ndarray

# 数组创建
有几种方法可以创建数组。

例如，你可以使用array函数从常规Python列表或元组中创建数组。得到的数组的类型是从Python列表中元素的类型推导出来的。

In [11]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [13]:
a.dtype

dtype('int32')

In [12]:
b = np.array([1.2, 3.5, 5.1])
b

array([1.2, 3.5, 5.1])

In [14]:
b.dtype

dtype('float64')

一个常见的错误，就是调用array的时候传入多个数字参数，而不是提供单个数字的列表类型作为参数。

In [15]:
a = np.array(1,2,3,4)    # WRONG

ValueError: only 2 non-keyword arguments accepted

In [16]:
a = np.array([1,2,3,4])  # RIGHT

array 还可以将序列的序列转换成二维数组，将序列的序列的序列转换成三维数组，等等。

In [17]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

也可以在创建时显式指定数组的类型：

In [18]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

通常，数组的元素最初是未知的，但它的大小是已知的。因此，NumPy提供了几个函数来创建具有初始占位符内容的数组。这就减少了数组增长的必要，因为数组增长的操作花费很大。

函数zeros创建一个由0组成的数组，函数 ones创建一个完整的数组，函数empty 创建一个数组，其初始内容是随机的，取决于内存的状态。默认情况下，创建的数组的dtype是 float64 类型的。

In [19]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones( (2,3,4), dtype=np.int16 )

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [21]:
np.empty( (2,3) ) 

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

为了创建数字组成的数组，NumPy提供了一个类似于range的函数，该函数返回数组而不是列表。

In [22]:
np.arange( 10, 30,5 )

array([10, 15, 20, 25])

In [23]:
np.arange( 0, 2, 0.3 )

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

当arange与浮点参数一起使用时，由于有限的浮点精度，通常不可能预测所获得的元素的数量。出于这个原因，通常最好使用linspace函数来接收我们想要的元素数量的函数，而不是步长（step）：

In [24]:
from numpy import pi

In [25]:
np.linspace( 0, 2, 9 ) # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [27]:
x = np.linspace( 0, 2*pi, 100 ) # useful to evaluate function at lots of points
f = np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

# 打印数组
当您打印数组时，NumPy以与嵌套列表类似的方式显示它，但具有以下布局：

最后一个轴从左到右打印，
倒数第二个从上到下打印，
其余部分也从上到下打印，每个切片用空行分隔。
然后将一维数组打印为行，将二维数据打印为矩阵，将三维数据打印为矩数组表。

In [28]:
a = np.arange(6)                         # 1d array
print(a)

[0 1 2 3 4 5]


In [29]:
b = np.arange(12).reshape(4,3)           # 2d array
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [30]:
c = np.arange(24).reshape(2,3,4)         # 3d array
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


如果数组太大而无法打印，NumPy会自动跳过数组的中心部分并仅打印角点：

In [31]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [32]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


要禁用此行为并强制NumPy打印整个数组，可以使用更改打印选项set_printoptions。

In [ ]:
np.set_printoptions(threshold=sys.maxsize)       # sys module should be imported

# 基本操作
数组上的算术运算符会应用到 元素 级别。下面是创建一个新数组并填充结果的示例：

In [33]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [35]:
c = a - b
c

array([20, 29, 38, 47])

In [36]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [37]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [38]:
a < 35

array([ True,  True, False, False])

与许多矩阵语言不同，乘积运算符*在NumPy数组中按元素进行运算。矩阵乘积可以使用@运算符（在python> = 3.5中）或dot函数或方法执行：

In [39]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )
print(A)
print(B)

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]


In [40]:
A * B # elementwise product

array([[2, 0],
       [0, 4]])

In [41]:
A @ B  # matrix product

array([[5, 4],
       [3, 4]])

In [42]:
A.dot(B)                    # another matrix product

array([[5, 4],
       [3, 4]])

某些操作（例如+=和 *=）会更直接更改被操作的矩阵数组而不会创建新矩阵数组。

In [49]:
>>> a = np.ones((2,3), dtype=int)
>>> b = np.random.random((2,3))

In [50]:
a

array([[1, 1, 1],
       [1, 1, 1]])

In [46]:
b

array([[0.96523402, 0.17315185, 0.40908148],
       [0.34349178, 0.08419162, 0.86885516]])

In [51]:
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [52]:
b += a
b

array([[3.73357236, 3.99382215, 3.55773174],
       [3.44436115, 3.60023434, 3.63511516]])

In [53]:
a += b # b is not automatically converted to integer type

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

当使用不同类型的数组进行操作时，结果数组的类型对应于更一般或更精确的数组（称为向上转换的行为）。

In [54]:
a = np.ones(3, dtype=np.int32)
a

array([1, 1, 1])

In [55]:
b = np.linspace(0, pi, 3)
b

array([0.        , 1.57079633, 3.14159265])

In [56]:
b.dtype.name

'float64'

In [57]:
c = a + b
c

array([1.        , 2.57079633, 4.14159265])

In [58]:
c.dtype.name

'float64'

In [59]:
d = np.exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [60]:
d.dtype.name

'complex128'

许多一元操作，例如计算数组中所有元素的总和，都是作为ndarray类的方法实现的。

In [61]:
a = np.random.random((2, 3))
a

array([[0.4150456 , 0.75124199, 0.19883789],
       [0.87022191, 0.12016339, 0.55200765]])

In [62]:
a.sum()

2.907518418713215

In [63]:
a.min()

0.1201633858947172

In [64]:
a.max()

0.8702219134302094

默认情况下，这些操作适用于数组，就像它是一个数字列表一样，无论其形状如何。但是，通过指定axis 参数，您可以沿数组的指定轴应用操作：

In [66]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [68]:
b.sum(axis=1)

array([ 6, 22, 38])

In [69]:
b.min(axis=1)

array([0, 4, 8])

In [70]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

# 通函数
NumPy提供熟悉的数学函数，例如sin，cos和exp。在NumPy中，这些被称为“通函数”（ufunc）。在NumPy中，这些函数在数组上按元素进行运算，产生一个数组作为输出。

In [71]:
B = np.arange(3)
B

array([0, 1, 2])

In [73]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [75]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [76]:
C = np.array([2., -1., 4.])
C

array([ 2., -1.,  4.])

In [77]:
np.add(B, C)

array([2., 0., 6.])

另见这些通函数

all， any， apply_along_axis， argmax， argmin， argsort， average， bincount， ceil， clip， conj， corrcoef， cov， cross， cumprod， cumsum， diff， dot， floor， inner， INV ， lexsort， max， maximum， mean， median， min， minimum， nonzero， outer， prod， re， round， sort， std， sum， trace， transpose， var， vdot， vectorize， where

# 索引、切片和迭代
一维的数组可以进行索引、切片和迭代操作的，就像 列表 和其他Python序列类型一样。

In [78]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [79]:
a[2]

8

In [80]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [82]:
a[:6:2] = -1000 # equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000

In [83]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [84]:
a[::-1]   # reversed a

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000], dtype=int32)

In [85]:
for i in a:
    print(i**(1/3.))

nan
1.0
nan
3.0
nan
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


D:\anacond3.5\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


多维的数组每个轴可以有一个索引。这些索引以逗号​​分隔的元组给出：

In [86]:
def f(x,y):
    return 10*x+y

In [87]:
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [88]:
b[2,3]

23

In [89]:
b[0:5,1]

array([ 1, 11, 21, 31, 41])

In [90]:
b[:,1]

array([ 1, 11, 21, 31, 41])

In [91]:
b[1:3,:]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

当提供的索引少于轴的数量时，缺失的索引被认为是完整的切片:

In [92]:
b[-1]

array([40, 41, 42, 43])

b[i] 方括号中的表达式 i 被视为后面紧跟着 : 的多个实例，用于表示剩余轴。NumPy也允许你使用三个点写为 b[i,...]。

三个点（ ... ）表示产生完整索引元组所需的冒号。例如，如果 x 是rank为的5数组（即，它具有5个轴），则：

x[1,2,...] 相当于 x[1,2,:,:,:]，

x[...,3] 等效于 x[:,:,:,:,3],

x[4,...,5,:] 等效于 x[4,:,:,5,:]。

In [93]:
c = np.array( [[[  0,  1,  2],
                 [ 10, 12, 13]],
               [[100,101,102],
                 [110,112,113]]])
c.shape

(2, 2, 3)

In [94]:
c[1,...]

array([[100, 101, 102],
       [110, 112, 113]])

In [95]:
c[...,2]

array([[  2,  13],
       [102, 113]])

对多维数组进行 迭代（Iterating） 是相对于第一个轴完成的：

In [96]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


但是，如果想要对数组中的每个元素执行操作，可以使用flat属性，该属性是数组的所有元素的迭代器：

In [97]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43
