# 形状操纵

# 改变数组的形状
一个数组的形状是由每个轴的元素数量决定的：

In [1]:
import numpy as np

In [2]:
a = np.floor(10*np.random.random((3, 4)))
a

array([[1., 7., 3., 2.],
       [2., 6., 9., 4.],
       [7., 2., 8., 0.]])

In [3]:
a.shape

(3, 4)

可以使用各种命令更改数组的形状。请注意，以下三个命令都返回一个修改后的数组，但不会更改原始数组：

In [4]:
a.ravel()  # returns the array, flattened

array([1., 7., 3., 2., 2., 6., 9., 4., 7., 2., 8., 0.])

In [5]:
a.reshape(6,2)  # returns the array with a modified shape

array([[1., 7.],
       [3., 2.],
       [2., 6.],
       [9., 4.],
       [7., 2.],
       [8., 0.]])

In [6]:
a.T  # returns the array, transposed

array([[1., 2., 7.],
       [7., 6., 2.],
       [3., 9., 8.],
       [2., 4., 0.]])

由 ravel() 产生的数组中元素的顺序通常是“C风格”，也就是说，最右边的索引“变化最快”，因此[0,0]之后的元素是[0,1] 。如果将数组重新整形为其他形状，则该数组将被视为“C风格”。NumPy通常创建按此顺序存储的数组，因此 ravel() 通常不需要复制其参数，但如果数组是通过获取另一个数组的切片或使用不常见的选项创建的，则可能需要复制它。还可以使用可选参数指示函数 ravel() 和 reshape()，以使用FORTRAN样式的数组，其中最左边的索引变化最快。

该reshape函数返回带有修改形状的参数，而该 ndarray.resize方法会修改数组本身：

In [7]:
a

array([[1., 7., 3., 2.],
       [2., 6., 9., 4.],
       [7., 2., 8., 0.]])

In [9]:
a.resize(2,6)
a

array([[1., 7., 3., 2., 2., 6.],
       [9., 4., 7., 2., 8., 0.]])

如果在 reshape 操作中将 size 指定为-1，则会自动计算其他的 size 大小：

In [10]:
a.reshape((3,-1))

array([[1., 7., 3., 2.],
       [2., 6., 9., 4.],
       [7., 2., 8., 0.]])

# 将不同数组堆叠在一起
几个数组可以沿不同的轴堆叠在一起，例如：

In [11]:
>>> a = np.floor(10*np.random.random((2,2)))
>>> a

array([[0., 5.],
       [1., 0.]])

In [12]:
>>> b = np.floor(10*np.random.random((2,2)))
>>> b

array([[1., 6.],
       [9., 3.]])

In [13]:
>>> np.vstack((a,b))

array([[0., 5.],
       [1., 0.],
       [1., 6.],
       [9., 3.]])

In [14]:
>>> np.hstack((a,b))

array([[0., 5., 1., 6.],
       [1., 0., 9., 3.]])

该函数将column_stack 1D数组作为列堆叠到2D数组中。它仅相当于 hstack2D数组：

In [15]:
>>> from numpy import newaxis
>>> np.column_stack((a,b))     # with 2D arrays

array([[0., 5., 1., 6.],
       [1., 0., 9., 3.]])

In [21]:
>>> a = np.array([4.,2.])
>>> b = np.array([3.,8.])

In [22]:
a

array([4., 2.])

In [23]:
b

array([3., 8.])

In [24]:
>>> np.column_stack((a,b))     # returns a 2D array

array([[4., 3.],
       [2., 8.]])

In [17]:
np.hstack((a,b))           # the result is different

array([4., 2., 3., 8.])

In [18]:
 a[:,newaxis]   

array([[4.],
       [2.]])

In [19]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

In [20]:
np.hstack((a[:,newaxis],b[:,newaxis]))   # the result is the same

array([[4., 3.],
       [2., 8.]])

另一方面，该函数ma.row_stack等效vstack 于任何输入数组。通常，对于具有两个以上维度的数组， hstack沿其第二轴vstack堆叠，沿其第一轴堆叠，并concatenate 允许可选参数给出连接应发生的轴的编号。

注意

在复杂的情况下，r_和c c_于通过沿一个轴堆叠数字来创建数组很有用。它们允许使用范围操作符(“：”)。

>>> np.r_[1:4,0,4]
array([1, 2, 3, 0, 4])
与数组一起用作参数时， r_ 和 c_ 在默认行为上类似于 vstack 和 hstack ，但允许使用可选参数给出要连接的轴的编号。

# 将一个数组拆分成几个较小的数组
使用hsplit，可以沿数组的水平轴拆分数组，方法是指定要返回的形状相等的数组的数量，或者指定应该在其之后进行分割的列：

In [25]:
>>> a = np.floor(10*np.random.random((2,12)))
>>> a

array([[1., 2., 5., 7., 8., 6., 2., 3., 7., 5., 2., 0.],
       [0., 6., 7., 0., 5., 3., 7., 0., 8., 6., 6., 6.]])

In [26]:
>>> np.hsplit(a,3)   # Split a into 3

[array([[1., 2., 5., 7.],
        [0., 6., 7., 0.]]), array([[8., 6., 2., 3.],
        [5., 3., 7., 0.]]), array([[7., 5., 2., 0.],
        [8., 6., 6., 6.]])]

In [27]:
np.hsplit(a,(3,4))   # Split a after the third and the fourth column

[array([[1., 2., 5.],
        [0., 6., 7.]]), array([[7.],
        [0.]]), array([[8., 6., 2., 3., 7., 5., 2., 0.],
        [5., 3., 7., 0., 8., 6., 6., 6.]])]

vsplit沿垂直轴分割，并array_split允许指定要分割的轴。

# 拷贝和视图
当计算和操作数组时，有时会将数据复制到新数组中，有时则不会。这通常是初学者混淆的根源。有三种情况：

# 完全不复制
简单分配不会复制数组对象或其数据。

In [28]:
>>> a = np.arange(12)
>>> b = a            # no new object is created
>>> b is a           # a and b are two names for the same ndarray object

True

In [29]:
>>> b.shape = 3,4    # changes the shape of a
>>> a.shape

(3, 4)

Python将可变对象作为引用传递，因此函数调用不会复制。

In [30]:
def f(x):
    print(id(x))

id(a)

61375016

In [31]:
f(a)

61375016


# 视图或浅拷贝
不同的数组对象可以共享相同的数据。该view方法创建一个查看相同数据的新数组对象。

In [32]:
>>> c = a.view()
>>> c is a

False

In [33]:
>>> c.base is a  

True

In [34]:
>>> c.flags.owndata

False

In [35]:
>>> c.shape = 2,6                      # a's shape doesn't change
>>> a.shape

(3, 4)

In [36]:
>>> c[0,4] = 1234                      # a's data changes
>>> a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

切片数组会返回一个视图：

In [37]:
>>> s = a[ : , 1:3]     # spaces added for clarity; could also be written "s = a[:,1:3]"
>>> s[:] = 10           # s[:] is a view of s. Note the difference between s=10 and s[:]=10
>>> a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

# 深拷贝
该copy方法生成数组及其数据的完整副本。

In [38]:
>>> d = a.copy()                          # a new array object with new data is created
>>> d is a

False

In [39]:
>>> d.base is a                           # d doesn't share anything with a

False

In [40]:
>>> d[0,0] = 9999
>>> a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

有时，如果不再需要原始数组，则应在切片后调用 copy。例如，假设a是一个巨大的中间结果，最终结果b只包含a的一小部分，那么在用切片构造b时应该做一个深拷贝：

In [41]:
>>> a = np.arange(int(1e8))
>>> b = a[:100].copy()
>>> del a  # the memory of ``a`` can be released.

如果改为使用 b = a[:100]，则 a 由 b 引用，并且即使执行 del a 也会在内存中持久存在。

# 功能和方法概述
以下是按类别排序的一些有用的NumPy函数和方法名称的列表。有关完整列表，请参阅参考手册里的常用API。

数组的创建（Array Creation） - arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity, linspace, logspace, mgrid, ogrid, ones, ones_like, zeros, zeros_like

转换和变换（Conversions） - ndarray.astype, atleast_1d, atleast_2d, atleast_3d, mat

操纵术（Manipulations） - array_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, ndarray.item, newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack

询问（Questions） - all, any, nonzero, where,

顺序（Ordering） - argmax, argmin, argsort, max, min, ptp, searchsorted, sort

操作（Operations） - choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask, real, sum

基本统计（Basic Statistics） - cov, mean, std, var

基本线性代数（Basic Linear Algebra） - cross, dot, outer, linalg.svd, vdot